export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const GET_ERROR = "GET_ERROR";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";

export const GET_BRANDS = "GET_BRANDS";
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND";
export const CREATE_BRANDS = "CREATE_BRANDS";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
